# i18n.py — Internationalization for Marketplace Client

TEXTS = {
    "pt": {
        "select_language": "🌐 Selecione o idioma / Select language:",
        "option_pt": "1. Português",
        "option_en": "2. English",
        "invalid_option": "❌ Opção inválida!",
        "welcome": "      📚 MARKETPLACE DE LIVROS",
        "menu_register": "3.  Cadastrar usuário",
        "menu_login": "4.  Login",
        "menu_add_book": "3.  Cadastrar livro",
        "menu_list_books": "1.  Listar livros (com filtros)",
        "menu_view_book": "2.  Ver livro por ID",
        "menu_edit_book": "4.  Editar livro",
        "menu_delete_book": "5.  Deletar livro",
        "menu_view_cart": "3.  Ver carrinho",
        "menu_add_cart": "4.  Adicionar item ao carrinho",
        "menu_update_cart": "5.  Atualizar quantidade no carrinho",
        "menu_remove_cart": "6.  Remover item do carrinho",
        "menu_clear_cart": "7.  Esvaziar carrinho",
        "menu_checkout": "8.  Finalizar compra (checkout)",
        "menu_history": "9.  Histórico de compras",
        "menu_sales_history": "6.  Histórico de vendas",
        "menu_logout": "7.  Logout",
        "menu_exit": "0.  Sair",
        "choice_prompt": "Escolha: ",
        "required_field": "Campo obrigatório!",
        "register_title": "--- CADASTRO DE USUÁRIO ---",
        "name": "Nome: ",
        "email": "Email: ",
        "password": "Senha: ",
        "user_type": "Tipo: 1=cliente | 2=vendedor",
        "register_success": "✅ Usuário cadastrado com sucesso!",
        "login_title": "--- LOGIN ---",
        "login_json": "1. Login com JSON",
        "login_oauth": "2. Login com OAuth2 (form)",
        "login_success": "✅ Login realizado com sucesso!",
        "login_first": "⚠️ Faça login primeiro!",
        "add_book_title": "--- CADASTRAR LIVRO ---",
        "book_name": "Nome do livro: ",
        "description": "Descrição: ",
        "author": "Autor: ",
        "price": "Preço (ex: 29.90): ",
        "stock": "Estoque: ",
        "book_added": "✅ Livro cadastrado!",
        "list_books_title": "--- LISTAR LIVROS ---",
        "filter_hint": "Deixe em branco para não filtrar",
        "filter_name": "Nome (ou parte): ",
        "filter_author": "Autor (ou parte): ",
        "filter_min_price": "Preço mínimo: ",
        "filter_max_price": "Preço máximo: ",
        "books_found": "📚 {count} {item}(s) encontrado(s)",
        "book_id": "ID do livro: ",
        "view_book_title": "📖",
        "edit_book_title": "--- EDITAR LIVRO ---",
        "edit_hint": "Deixe em branco para manter o valor atual",
        "delete_confirm": "Tem certeza? (s/n): ",
        "deleted": "✅ Deletado!",
        "cart_title": "🛒 Carrinho",
        "cart_active": "Ativo",
        "cart_finished": "Finalizado",
        "cart_empty": "(vazio)",
        "cart_total": "TOTAL",
        "add_cart_title": "--- ADICIONAR AO CARRINHO ---",
        "quantity": "Quantidade: ",
        "item_added": "✅ Item adicionado!",
        "cart_total_label": "Total do carrinho",
        "update_cart_title": "--- ATUALIZAR QUANTIDADE ---",
        "new_quantity": "Nova quantidade (0 para remover): ",
        "updated": "✅ Atualizado!",
        "remove_cart_title": "--- REMOVER DO CARRINHO ---",
        "item_removed": "✅ Item removido!",
        "clear_cart_title": "--- ESVAZIAR CARRINHO ---",
        "cart_cleared": "✅ Carrinho esvaziado!",
        "checkout_title": "--- FINALIZAR COMPRA ---",
        "confirm_purchase": "Confirmar compra? (s/n): ",
        "purchase_success": "✅ Compra finalizada!",
        "total_paid": "Total pago",
        "history_title": "--- HISTÓRICO DE COMPRAS ---",
        "no_purchases": "Nenhuma {item} realizada.",
        "purchase": "Compra",
        "exit": "👋 Até mais!",
        "cancelled": "Cancelado.",
        "error": "❌ Erro",
        "not_logged_in": "👤 Não logado",
        "user_info_error": "⚠️ Não foi possível carregar informações do usuário",
        "purchases": "🛒 Compras",
        "select_book": "Selecione o livro (número ou ID): ",
        "selected": "Selecionado",
        "max_stock": "máx",
        "book_not_found_results": "❌ Livro não encontrado nos resultados.",
        "stock_error": "❌ Erro: Apenas",
        "in_stock": "em estoque!",
        "sales_history_title": "--- HISTÓRICO DE VENDAS ---",
        "no_sales": "Nenhuma venda realizada.",
        "books_sold": "Livros vendidos",
        "total_books_sold": "Total de livros vendidos",
        "total_revenue": "Faturamento total",
        "unit_price": "Preço unitário",
        "revenue": "Receita",
        "qty_sold": "Qtd vendida",
    },
    "en": {
        "select_language": "🌐 Select language / Selecione o idioma:",
        "option_pt": "1. Português",
        "option_en": "2. English",
        "invalid_option": "❌ Invalid option!",
        "welcome": "      📚 BOOK MARKETPLACE",
        "menu_register": "3.  Register user",
        "menu_login": "4.  Login",
        "menu_add_book": "3.  Add book",
        "menu_list_books": "1.  List books (with filters)",
        "menu_view_book": "2.  View book by ID",
        "menu_edit_book": "4.  Edit book",
        "menu_delete_book": "5.  Delete book",
        "menu_view_cart": "3.  View cart",
        "menu_add_cart": "4.  Add item to cart",
        "menu_update_cart": "5.  Update quantity in cart",
        "menu_remove_cart": "6.  Remove item from cart",
        "menu_clear_cart": "7.  Clear cart",
        "menu_checkout": "8.  Checkout",
        "menu_history": "9.  Purchase history",
        "menu_sales_history": "6.  Sales history",
        "menu_logout": "7.  Logout",
        "menu_exit": "0.  Exit",
        "choice_prompt": "Choice: ",
        "required_field": "Required field!",
        "register_title": "--- USER REGISTRATION ---",
        "name": "Name: ",
        "email": "Email: ",
        "password": "Password: ",
        "user_type": "Type: 1=client | 2=seller",
        "register_success": "✅ User registered successfully!",
        "login_title": "--- LOGIN ---",
        "login_json": "1. Login with JSON",
        "login_oauth": "2. Login with OAuth2 (form)",
        "login_success": "✅ Login successful!",
        "login_first": "⚠️ Please login first!",
        "add_book_title": "--- ADD BOOK ---",
        "book_name": "Book name: ",
        "description": "Description: ",
        "author": "Author: ",
        "price": "Price (ex: 29.90): ",
        "stock": "Stock: ",
        "book_added": "✅ Book added!",
        "list_books_title": "--- LIST BOOKS ---",
        "filter_hint": "Leave blank to not filter",
        "filter_name": "Name (or part): ",
        "filter_author": "Author (or part): ",
        "filter_min_price": "Min price: ",
        "filter_max_price": "Max price: ",
        "books_found": "📚 {count} {item}(s) found",
        "book_id": "Book ID: ",
        "view_book_title": "📖",
        "edit_book_title": "--- EDIT BOOK ---",
        "edit_hint": "Leave blank to keep current value",
        "delete_confirm": "Are you sure? (y/n): ",
        "deleted": "✅ Deleted!",
        "cart_title": "🛒 Cart",
        "cart_active": "Active",
        "cart_finished": "Finished",
        "cart_empty": "(empty)",
        "cart_total": "TOTAL",
        "add_cart_title": "--- ADD TO CART ---",
        "quantity": "Quantity: ",
        "item_added": "✅ Item added!",
        "cart_total_label": "Cart total",
        "update_cart_title": "--- UPDATE QUANTITY ---",
        "new_quantity": "New quantity (0 to remove): ",
        "updated": "✅ Updated!",
        "remove_cart_title": "--- REMOVE FROM CART ---",
        "item_removed": "✅ Item removed!",
        "clear_cart_title": "--- CLEAR CART ---",
        "cart_cleared": "✅ Cart cleared!",
        "checkout_title": "--- CHECKOUT ---",
        "confirm_purchase": "Confirm purchase? (y/n): ",
        "purchase_success": "✅ Purchase completed!",
        "total_paid": "Total paid",
        "history_title": "--- PURCHASE HISTORY ---",
        "no_purchases": "No {item} made.",
        "purchase": "Purchase",
        "exit": "👋 Goodbye!",
        "cancelled": "Cancelled.",
        "error": "❌ Error",
        "not_logged_in": "👤 Not logged in",
        "user_info_error": "⚠️ Could not load user info",
        "purchases": "🛒 Purchases",
        "select_book": "Select book (number or ID): ",
        "selected": "Selected",
        "max_stock": "max",
        "book_not_found_results": "❌ Book not found in results.",
        "stock_error": "❌ Error: Only",
        "in_stock": "in stock!",
        "sales_history_title": "--- SALES HISTORY ---",
        "no_sales": "No sales made.",
        "books_sold": "Books sold",
        "total_books_sold": "Total books sold",
        "total_revenue": "Total revenue",
        "unit_price": "Unit price",
        "revenue": "Revenue",
        "qty_sold": "Qty sold",
    }
}


def get_texts(lang: str) -> dict:
    """Return translations for the selected language."""
    return TEXTS.get(lang, TEXTS["pt"])